### ISSUE TITLE
いまChatworkのとあるプロジェクトでAkka Clusterの負荷試験やってるんだけど…その様子を見ませんか?

### ISSUE THREAD

**Issue by yoshiyoshifujii** [scalamatsuri/2020.unconference#14]
# Mandatory / 必須欄
My Discord Account: yoshiyoshifujii
Session Language: Japanese
Detail:
Chatwork株式会社でとあるプロジェクトにて、Akka Clusterで構築したアプリケーションの負荷試験をしております。
今日は、いつもと同じように、モブワークして、進捗を出そうと思います。
負荷をかけている間にざっくばらんに説明したり、QAとかできますので、一緒に進捗をだしませんか?

# Optional / 希望欄
Session Length: 120 minutes
Time preference: [12:00 - 20:00] in JST (UTC+9)

# Comment for audience
このセッションを聞きたい方は、こちらに👍を付けて下さい！

Please show your reaction e.g.👍 if you want to listen this session.

**Comment by j5ik2o** [comment]
以下はこのIssueとマージできそうです。
https://github.com/scalamatsuri/2020.unconference/issues/12

**Comment by taisukeoe** [comment]
#12 と合同セッションになったため、こちらは閉じます。
