### ISSUE TITLE
Recursion schemes from the ground up

### ISSUE THREAD

**Issue by nrinaudo** [scalamatsuri/2020.unconference#2]
# Mandatory / 必須欄
- My Discord Account: Nicolas#7889
- Session Language: English

Detail:
I'm working on a talk about recursion schemes and am looking for opportunities to try it out on actual people - speaking at my rubber duck doesn't quite work the same way.

Here's the elevator pitch:

Recursion schemes often come up as "something real FP programmers must know", which I can't help but take as a bit of a challenge.

The purpose of this talk is to help you, too, become a real FP programmer and, should help you understand when, and more importantly when not, to use recursion schemes.

# Optional / 希望欄 
- Session Length: ~60 minutes
- Time preference: anytime in 12:00 - 18:00

**Comment by nrinaudo** [comment]
It turns out I will not be able to attend for family reasons. Apologies :/

**Comment by taisukeoe** [comment]
@nrinaudo Thank you for letting us know. See you next time!
